apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ycgjgze5l-go-gitops
  description: This is GitOps manifest for ycgjgze5l-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ycgjgze5l-go
    backstage.io/kubernetes-id: ycgjgze5l-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ycgjgze5l-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ycgjgze5l-go
