apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ycgjgze5l-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ycgjgze5l-go 
  name: ycgjgze5l-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ycgjgze5l-go 
